main.datasource.url =  jdbc:postgresql://localhost:5432/projectmgt
main.datasource.username = postgres
main.datasource.password = password
main.datasource.driver-class-name=org.postgresql.Driver

main.liquibase.change-log=com/company/projectmgt/liquibase/changelog.xml

jmix.ui.login-view-id = LoginView
jmix.ui.main-view-id = MainView
jmix.ui.menu-config = com/company/projectmgt/menu.xml
jmix.ui.composite-menu = true

ui.login.defaultUsername = admin
ui.login.defaultPassword = admin

jmix.core.available-locales = en

enable-anonymous-access=true

jmix.rest.csrf-protection-enabled = false

jmix.rest.anonymous-url-patterns = \
  /rest/services/**,\
  /rest/**,\
  /api/v1/**

#jmix.rest.enabled = true


spring.security.oauth2.authorizationserver.client.my-client.registration.client-id=your-client-id
spring.security.oauth2.authorizationserver.client.my-client.registration.client-secret=your-client-secret
spring.security.oauth2.authorizationserver.client.my-client.registration.client-authentication-methods=client_secret_basic
spring.security.oauth2.authorizationserver.client.my-client.registration.authorization-grant-types=authorization_code,refresh_token
spring.security.oauth2.authorizationserver.client.my-client.registration.redirect-uris=http://127.0.0.1:8080/login/oauth2/code/my-client
spring.security.oauth2.authorizationserver.client.my-client.registration.scopes=openid,profile,email

spring.security.oauth2.client.registration.google.client-id=55072330303-d55n0bqncmf6kc4af0o936e5gov41m8e.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/api/v1
spring.security.oauth2.client.registration.google.scope=email,profile,openid


#jmix.security.oauth2.default-provider=google


jmix.authserver.client.my-client.resource-roles=ANONYMOUS

# Launch the default browser when starting the application in development mode
vaadin.launch-browser = false

# Use pnpm to speed up project initialization and save disk space
vaadin.pnpm.enable = true

logging.level.org.atmosphere = warn

# 'debug' level logs SQL generated by EclipseLink ORM
logging.level.eclipselink.logging.sql = info

# 'debug' level logs data store operations
logging.level.io.jmix.core.datastore = info

# 'debug' level logs access control constraints
logging.level.io.jmix.core.AccessLogger = debug

# 'debug' level logs all Jmix debug output
logging.level.io.jmix = info